import timelineJson from "../public/timeline.json";

export type Tap = { frame: number; x: number; y: number };
export type Sentence = { file: string; text: string; from: number; durationInFrames: number };
export type Scene = {
  id: string;
  kind: "card" | "phone" | "desktop";
  from: number;
  durationInFrames: number;
  trimBefore: number;
  taps: Tap[];
  sentences: Sentence[];
};
export type Timeline = { fps: number; durationInFrames: number; scenes: Scene[] };

// Generated by scripts/build-timeline.mjs from the voice and capture runs.
export const timeline = timelineJson as Timeline;

export const sceneById = (id: string): Scene => {
  const scene = timeline.scenes.find((s) => s.id === id);
  if (!scene) throw new Error(`No scene ${id} in timeline.json`);
  return scene;
};

export const COLORS = {
  ink: "#120d26",
  deep: "#1d1442",
  violet: "#7c3aed",
  lilac: "#c4b5fd",
  white: "#ffffff",
  muted: "#b8b0d9",
};
export const FONT = "Inter, 'Segoe UI', system-ui, -apple-system, sans-serif";
